### ISSUE TITLE
Could not resolve type id 'AlexaSkillEvent.ProactiveSubscriptionChanged'

### ISSUE THREAD

**Issue by LorenzNickel** [amzn/alexa-skills-kit-java#170]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior

As far as I understood if someone toggles notifications for my skill, my skill is triggered with the request-type "AlexaSkillEvent.ProactiveSubscriptionChanged" and I need the data provided here to send notifications to the user.

## Current Behavior

After I added the necessary lines to my skill.json my skill is working fine, but I always get an error multiple times per request in CloudWatch (skill is hosted in AWS Lambda) and my skill does not seems to be triggered when notifications are enabled or disabled and I think the following error has something to do with this.
```
Deserialization error: com.amazon.ask.exception.AskSdkException
com.amazon.ask.exception.AskSdkException: Deserialization error
at com.amazon.ask.util.impl.JacksonJsonUnmarshaller.unmarshall(JacksonJsonUnmarshaller.java:50)
at com.amazon.ask.impl.AbstractSkill.execute(AbstractSkill.java:44)
at com.amazon.ask.AlexaSkill.execute(AlexaSkill.java:22)
at com.amazon.ask.SkillStreamHandler.handleRequest(SkillStreamHandler.java:71)
at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
Caused by: com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve type id 'AlexaSkillEvent.ProactiveSubscriptionChanged' as a subtype of [simple type, class com.amazon.ask.model.Request]: known type ids = [Alexa.Presentation.APL.UserEvent, AlexaHouseholdListEvent.ItemsCreated, AlexaHouseholdListEvent.ItemsDeleted, AlexaHouseholdListEvent.ItemsUpdated, AlexaHouseholdListEvent.ListCreated, AlexaHouseholdListEvent.ListDeleted, AlexaHouseholdListEvent.ListUpdated, AlexaSkillEvent.SkillAccountLinked, AlexaSkillEvent.SkillDisabled, AlexaSkillEvent.SkillEnabled, AlexaSkillEvent.SkillPermissionAccepted, AlexaSkillEvent.SkillPermissionChanged, AudioPlayer.PlaybackFailed, AudioPlayer.PlaybackFinished, AudioPlayer.PlaybackNearlyFinished, AudioPlayer.PlaybackStarted, AudioPlayer.PlaybackStopped, Connections.Request, Connections.Response, Display.ElementSelected, GameEngine.InputHandlerEvent, IntentRequest, LaunchRequest, Messaging.MessageReceived, PlaybackController.NextCommandIssued, PlaybackController.PauseCommandIssued, PlaybackController.PlayCommandIssued, PlaybackController.PreviousCommandIssued, SessionEndedRequest, System.ExceptionEncountered] (for POJO property 'request')
at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: com.amazon.ask.model.RequestEnvelope$Builder["request"])
at com.fasterxml.jackson.databind.exc.InvalidTypeIdException.from(InvalidTypeIdException.java:43)
at com.fasterxml.jackson.databind.DeserializationContext.invalidTypeIdException(DeserializationContext.java:1628)
at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownTypeId(DeserializationContext.java:1186)
at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._handleUnknownTypeId(TypeDeserializerBase.java:291)
at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._findDeserializer(TypeDeserializerBase.java:162)
at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:113)
at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:97)
at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:254)
at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeSetAndReturn(MethodProperty.java:151)
at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.vanillaDeserialize(BuilderBasedDeserializer.java:269)
at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserialize(BuilderBasedDeserializer.java:193)
at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3972)
at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2264)
at com.fasterxml.jackson.databind.ObjectMapper.treeToValue(ObjectMapper.java:2746)
at com.amazon.ask.util.impl.JacksonJsonUnmarshaller.unmarshall(JacksonJsonUnmarshaller.java:48)
... 6 more
```

## Steps to Reproduce (for bugs)

I'm trying to handle the event with the following class, it doesn't even change anything if I add this class or have it removed. I was also wondering what I should return.
```
public class ProactiveEventHandler implements RequestHandler {

    @Override
    public boolean canHandle(HandlerInput input) {

        return (input.getRequestEnvelope().getRequest().getType() == "AlexaSkillEvent.ProactiveSubscriptionChanged");
    }

    @Override
    public Optional<Response> handle(HandlerInput input) {
        System.out.println("AWS User " + input.getRequestEnvelope().getContext().getSystem().getUser().getUserId());
        System.out.println("API Endpoint " + input.getRequestEnvelope().getContext().getSystem().getApiEndpoint());
        return null;
    }
}
```

## Context

I'm not able to find out if users have notifications enabled and to get their userID and apiEndpoint (I'm not sure I should be able to find if notifications are enabled, but I need to access the id and endpoint). Also I want to get rid of having always this bug in my logs.

## Your Environment

* ASK Java SDK version used: 2.11.2
* Operating System and version: Built on Windows 10, running as LambdaFunction in Ireland

## Java Info

* Java version used for development: 1.8.0_191

**Comment by Chris-Liao** [comment]
Hey @BlockLabTV, we haven't support Proactive Events API in SDK thus throwing exception when trying to deserialize request to subscription event. We have feature request to add it. Please stay tuned. Thanks.

**Comment by pbheemag** [comment]
Hi @BlockLabTV , we’ve communicated your feedback to the team to make sure the work is tracked. Closing this issue. Feel free to reopen for any questions.
