### ISSUE TITLE
An error occurred during JSON parsing

### ISSUE THREAD

**Issue by skyfall174** [amzn/alexa-skills-kit-java#208]
## An error occurred during JSON parsing

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

<code>
<pre>
An error occurred during JSON parsing: java.lang.RuntimeException
java.lang.RuntimeException: An error occurred during JSON parsing
Caused by: java.io.UncheckedIOException: com.fasterxml.jackson.databind.JsonMappingException: No suitable constructor found for type [simple type, class com.amazon.ask.dispatcher.request.handler.HandlerInput]: can not instantiate from JSON object (missing default constructor or creator, or perhaps need to add/enable type information?)
at [Source: lambdainternal.util.NativeMemoryAsInputStream@2b2948e2; line: 1, column: 2]
Caused by: com.fasterxml.jackson.databind.JsonMappingException: No suitable constructor found for type [simple type, class com.amazon.ask.dispatcher.request.handler.HandlerInput]: can not instantiate from JSON object (missing default constructor or creator, or perhaps need to add/enable type information?)
at [Source: lambdainternal.util.NativeMemoryAsInputStream@2b2948e2; line: 1, column: 2]
at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1106)
at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:296)
at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:133)
at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1511)
at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1102)
</pre>
</code>

## Expected Behavior
Call my handler

## Current Behavior
Fail with exception

## Steps to Reproduce (for bugs)
```
  mvn org.apache.maven.plugins:maven-assembly-plugin:2.6:assembly -DdescriptorId=jar-with-dependencies package
  upload to lambda function AWS
```

## Your Environment

* ASK Java SDK version used: 2.3.4
* Operating System and version: Windows 10

## Java Info

* Java version used for development: 8

**Comment by pbheemag** [comment]
Hi @skyfall174 ,
Could you kindly provide more information (what we're trying to do) about the issue you're facing? Also, kindly update the issue with the full stack trace. It would expedite the process of getting the issue fixed.

**Comment by pbheemag** [comment]
Closing this issue due to developer inactivity. Feel free to reopen the issue if the issue persists.

**Comment by ZMarouani** [comment]
Hello , i have the same problem when trying to run a lambda function from Intellij editor (java : Corretto 11 )   : 

```
Invoking com.lambda.java.LambdaJavaFunction (java11)
Skip pulling image and use local one: amazon/aws-sam-cli-emulation-image-java11:rapid-1.18.1.

Mounting C:\Users\marouanizied\Desktop\Aws-workspace\ESLambdaFunctionJava\src\main\.aws-sam\build\Function as /var/task:ro,delegated inside runtime container
START RequestId: *** Version: $LATEST
Picked up _JAVA_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,quiet=y,address=*:61622 -XX:MaxHeapSize=2834432k -XX:MaxMetaspaceSize=163840k -XX:ReservedCodeCacheSize=81920k -XX:+UseSerialGC -XX:-TieredCompilation -Djava.net.preferIPv4Stack=true
Connected to the target VM, address: 'localhost:61622', transport: 'socket'
{"errorMessage":"An error occurred during JSON parsing","errorType":"java.lang.RuntimeException","stackTrace":[],"cause":{"errorMessage":"com.amazonaws.lambda.thirdparty.com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'so': was expecting (JSON String, Number (or 'NaN'/'INF'/'+INF'), Array, Object or token 'null', 'true' or 'false')\n at [Source: (ByteArrayInputStream); line: 1, column: 4]","errorType":"java.io.UncheckedIOException","stackTrace":["com.amazonaws.services.lambda.runtime.serialization.factories.JacksonFactory$InternalSerializer.fromJson(JacksonFactory.java:184)"],"cause":{"errorMessage":"Unrecognized token 'so': was expecting (JSON String, Number (or 'NaN'/'INF'/'+INF'), Array, Object or token 'null', 'true' or 'false')\n at [Source: (ByteArrayInputStream); line: 1, column: 4]","errorType":"com.amazonaws.lambda.thirdparty.com.fasterxml.jackson.core.JsonParseException","stackTrace":["com.amazonaws.lambda.thirdparty.com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1840)","com.amazonaws.lambda.thirdparty.com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:722)","com.amazonaws.lambda.thirdparty.com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidToken(UTF8StreamJsonParser.java:3556)","com.amazonaws.lambda.thirdparty.com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2651)","com.amazonaws.lambda.thirdparty.com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:856)","com.amazonaws.lambda.thirdparty.com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:753)","com.amazonaws.lambda.thirdparty.com.fasterxml.jackson.databind.ObjectReader._initForReading(ObjectReader.java:357)","com.amazonaws.lambda.thirdparty.com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1704)","com.amazonaws.lambda.thirdparty.com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1228)","com.amazonaws.services.lambda.runtime.serialization.factories.JacksonFactory$InternalSerializer.fromJson(JacksonFactory.java:182)"]}}}An error occurred during JSON parsing: java.lang.RuntimeException
java.lang.RuntimeException: An error occurred during JSON parsing
Caused by: java.io.UncheckedIOException: com.amazonaws.lambda.thirdparty.com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'so': was expecting (JSON String, Number (or 'NaN'/'INF'/'+INF'), Array, Object or token 'null', 'true' or 'false')
 at [Source: (ByteArrayInputStream); line: 1, column: 4]
	at com.amazonaws.services.lambda.runtime.serialization.factories.JacksonFactory$InternalSerializer.fromJson(JacksonFactory.java:184)
Caused by: com.amazonaws.lambda.thirdparty.com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'so': was expecting (JSON String, Number (or 'NaN'/'INF'/'+INF'), Array, Object or token 'null', 'true' or 'false')
 at [Source: (ByteArrayInputStream); line: 1, column: 4]
	at com.amazonaws.lambda.thirdparty.com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1840)
	at com.amazonaws.lambda.thirdparty.com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:722)
	at com.amazonaws.lambda.thirdparty.com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidToken(UTF8StreamJsonParser.java:3556)
	at com.amazonaws.lambda.thirdparty.com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2651)
	at com.amazonaws.lambda.thirdparty.com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:856)
	at com.amazonaws.lambda.thirdparty.com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:753)
	at com.amazonaws.lambda.thirdparty.com.fasterxml.jackson.databind.ObjectReader._initForReading(ObjectReader.java:357)
	at com.amazonaws.lambda.thirdparty.com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1704)
	at com.amazonaws.lambda.thirdparty.com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1228)
	at com.amazonaws.services.lambda.runtime.serialization.factories.JacksonFactory$InternalSerializer.fromJson(JacksonFactory.java:182)

END RequestId: ***
REPORT RequestId: ****	Init Duration: 0.08 ms	Duration: 876.95 ms	Billed Duration: 900 ms	Memory Size: 128 MB	Max Memory Used: 128 MB	
Disconnected from the target VM, address: 'localhost:61622', transport: 'socket'
```

Also i read on another forum that it might be a problem between aws and json format : 
https://stackoverflow.com/questions/35545642/error-executing-hello-world-for-aws-lambda-in-java

Maybe i shouldn't use the Jackson's java dependency for json  ? 
compile group: 'com.fasterxml.jackson.core', name: 'jackson-databind', version: '2.0.1'

my code for the lambda function handler  :
 
```RUBY
public class LambdaJavaFunction implements RequestHandler<Object, Object> {

    @Override
    public Object handleRequest(Object input, Context context) {
             //Other code 

            //Search response
            SearchResponse searchResponse = client.search(searchRequest, RequestOptions.DEFAULT);
            SearchHits hits = searchResponse.getHits();
            SearchHit[] searchHitsArray = hits.getHits();

            for (SearchHit hit : searchHitsArray) {
                Map<String, Object> sourceAsMap = hit.getSourceAsMap();
                String documentNameField = (String) sourceAsMap.get("name");

                logger.log(Level.INFO, documentNameField);
            }

            client.close();
            return hits;

        } catch (IOException e) {
            e.printStackTrace();
        } finally {
            try {
                if (client != null) {
                    client.close();
                }
            } catch (IOException e) {
                e.printStackTrace();
            }
        }

        return null;

    }
}
```
