### ISSUE TITLE
Will Not build as maven project

### ISSUE THREAD

**Issue by UltimateOgee** [amzn/alexa-skills-kit-java#41]
I love this code as it was a perfect way to get started on any alexa java skill. 

when I try compiling it using cmd now using the command outlined in the documentation now, as opposed to two months ago, I get the following error:

Exception in thread "main" java.lang.NoClassDefFoundError: org/codehaus/plexus/logging/LoggerManager
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at org.codehaus.plexus.classworlds.launcher.Launcher.getEnhancedMainMethod(Launcher.java:172)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:268)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.ClassNotFoundException: org.codehaus.plexus.logging.LoggerManager
        at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
        ... 10 more

Any ideas? Thank you!

**Comment by UltimateOgee** [comment]
I figured this out on my own, the Maven version I was using was simply too old. After updating the version, everything works perfectly.
