### ISSUE TITLE
build error when run 'mvn assembly:assembly -DdescriptorId=jar-with-dependencies package'.

### ISSUE THREAD

**Issue by neoskywalker7** [amzn/alexa-skills-kit-java#7]
Hi, I try to run 'mvn assembly:assembly -DdescriptorId=jar-with-dependencies package' following your instruction. But I met some unexpected question. Why did it happen?
I really wanna know how to fix it

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project alexa-skills-kit-samples: Compilation failure: Compilation failure:
[ERROR] /home/local/ANT/longzhen/Downloads/alexa-skills-kit-java-master/samples/src/main/java/Launcher.java:[22,34] package org.eclipse.jetty.util.ssl does not exist
[ERROR] /home/local/ANT/longzhen/Downloads/alexa-skills-kit-java-master/samples/src/main/java/Launcher.java:[65,9] cannot find symbol
[ERROR] symbol:   class SslContextFactory
[ERROR] location: class Launcher
[ERROR] /home/local/ANT/longzhen/Downloads/alexa-skills-kit-java-master/samples/src/main/java/Launcher.java:[65,67] cannot access org.eclipse.jetty.util.component.ContainerLifeCycle
[ERROR] class file for org.eclipse.jetty.util.component.ContainerLifeCycle not found
[ERROR] /home/local/ANT/longzhen/Downloads/alexa-skills-kit-java-master/samples/src/main/java/Launcher.java:[78,24] cannot access org.eclipse.jetty.util.component.LifeCycle
[ERROR] class file for org.eclipse.jetty.util.component.LifeCycle not found
[ERROR] /home/local/ANT/longzhen/Downloads/alexa-skills-kit-java-master/samples/src/main/java/Launcher.java:[82,15] cannot access org.eclipse.jetty.util.Attributes
[ERROR] class file for org.eclipse.jetty.util.Attributes not found
[ERROR] /home/local/ANT/longzhen/Downloads/alexa-skills-kit-java-master/samples/src/main/java/Launcher.java:[85,16] cannot access org.eclipse.jetty.util.component.Graceful
[ERROR] class file for org.eclipse.jetty.util.component.Graceful not found
[ERROR] /home/local/ANT/longzhen/Downloads/alexa-skills-kit-java-master/samples/src/main/java/Launcher.java:[86,15] cannot access org.eclipse.jetty.util.component.Destroyable
[ERROR] class file for org.eclipse.jetty.util.component.Destroyable not found
[ERROR] /home/local/ANT/longzhen/Downloads/alexa-skills-kit-java-master/samples/src/main/java/Launcher.java:[87,28] cannot access javax.servlet.http.HttpServlet
[ERROR] class file for javax.servlet.http.HttpServlet not found
[ERROR] /home/local/ANT/longzhen/Downloads/alexa-skills-kit-java-master/samples/src/main/java/Launcher.java:[87,16] cannot access org.eclipse.jetty.util.component.AbstractLifeCycle
[ERROR] class file for org.eclipse.jetty.util.component.AbstractLifeCycle not found
[ERROR] /home/local/ANT/longzhen/Downloads/alexa-skills-kit-java-master/samples/src/main/java/Launcher.java:[88,28] cannot access javax.servlet.Servlet
[ERROR] class file for javax.servlet.Servlet not found
[ERROR] /home/local/ANT/longzhen/Downloads/alexa-skills-kit-java-master/samples/src/main/java/Launcher.java:[89,15] method start in class org.eclipse.jetty.server.Server cannot be applied to given types;
[ERROR] required: org.eclipse.jetty.util.component.LifeCycle
[ERROR] found: no arguments
[ERROR] reason: actual and formal argument lists differ in length
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project alexa-skills-kit-samples: Compilation failure
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.MojoExecutor.executeForkedExecutions(MojoExecutor.java:365)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:199)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
    at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:911)
    at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:129)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)

**Comment by neoskywalker7** [comment]
I solve it

**Comment by terrayuku** [comment]
how?

**Comment by jawadhussain** [comment]
Delete contents from C:\Users\user.m2\repository. Either everything or selectively - your choice.
Then use the command prompt to force download jars and build
mvn clean install

**Comment by bclement-amazon** [comment]
closing this issue as it appears to have been resolved
Thanks @jawadhussain for the instructions.
